version: '2.3'
services:
  factorio:
    build: .
    ports:
     - "34198:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - type: bind
       source: C:/factorio1
       target: /factorio

volumes: 
  factorio: 